### ISSUE TITLE
Add Function Classes from Mambaformers Paper

### ISSUE THREAD

**Issue by KesavaViswanadha** [in-context-learning-2024/in-context#59]
Create the following function classes: Orthogonal-outlier regression, Many-outlier regression, Sparse parity, Chain-of-Thought I/O, Vector-valued MQAR   

<img width="783" alt="image" src="https://github.com/in-context-learning-2024/in-context/assets/79319318/e355ebb2-2ac3-4ec6-b71c-28d17924e221">

link to mambaformers paper codebase that implements this: https://github.com/krafton-ai/mambaformer-icl/blob/29349899e409048dbfc4b5955ee11879f12bcf2e/src/tasks.py

**Comment by nelson-lojo** [comment]
Closing issue that should've been closed automatically
